### ISSUE TITLE
Articles

### ISSUE THREAD

**Issue by SubhiH** [italojs/awesome-opencv#5]
Image Processing Best Practices — C++
https://medium.com/@soubhimhadri/image-processing-best-practices-c-280caadacb82

Face Detection in IOS
https://medium.com/@soubhimhadri/face-detection-in-ios-4330961e9865

**Comment by italojs** [comment]
Added in commit https://github.com/italojs/awesome-opencv/commit/93b71527fd7917b266b22131f1fbab7624fa8016 :) tks!
